apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cron
  namespace: devproject
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox
              command: ["echo", "Hello test!!!"]
          restartPolicy: Never
