apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
  namespace: devproject
spec:
  ttlSecondsAfterFinished: 40
  template:
    spec:
      containers:
        -  name: busybox
           image: busybox
           command: ["echo", "Hello karty!!!"]
      restartPolicy: Never
